const wordData = [
  { word: "笔电", pinyin: "bidian", meaning: "laptop computer" },
  { word: "产品", pinyin: "chanpin", meaning: "product" },
  { word: "平板", pinyin: "pingban", meaning: "tablet computer" },
  { word: "差别", pinyin: "chabie", meaning: "difference" },
  { word: "说明", pinyin: "shuoming", meaning: "to explain; explanation" },
  { word: "功能", pinyin: "gongneng", meaning: "function; feature" },
  { word: "轻", pinyin: "qing", meaning: "light (in weight)" },
  { word: "出差", pinyin: "chuchai", meaning: "business trip" },
  { word: "不如", pinyin: "buru", meaning: "not as good as" },
  { word: "大多数", pinyin: "daduoshu", meaning: "most; majority" },
  { word: "背包", pinyin: "beibao", meaning: "backpack" },
  { word: "不管", pinyin: "buguan", meaning: "no matter; regardless of" },
  { word: "跟", pinyin: "gen", meaning: "with; and" },
  { word: "好用", pinyin: "haoyong", meaning: "easy to use; handy" },
  { word: "新闻", pinyin: "xinwen", meaning: "news" },
  { word: "抱怨", pinyin: "baoyuan", meaning: "to complain" },
  { word: "电池", pinyin: "dianchi", meaning: "battery" },
  { word: "正常", pinyin: "zhengchang", meaning: "normal; functioning properly" },
  { word: "保证", pinyin: "baozheng", meaning: "to guarantee; warranty" },
  { word: "修理", pinyin: "xiuli", meaning: "to repair" },
  { word: "恐怕", pinyin: "kongpa", meaning: "I'm afraid that; probably" },
  { word: "改天", pinyin: "gaitian", meaning: "another day; some other time" },
  { word: "传真机", pinyin: "chuanzhenji", meaning: "fax machine" },
  { word: "传真", pinyin: "chuanzhen", meaning: "to fax; fax" },
  { word: "打折", pinyin: "dazhe", meaning: "to have a discount" },
  { word: "超过", pinyin: "chaoguo", meaning: "to exceed; to be more than" },
  { word: "把握", pinyin: "bawo", meaning: "to seize; to grasp (opportunity)" },
  { word: "大约", pinyin: "dayue", meaning: "approximately; about" },
  { word: "能够", pinyin: "nenggou", meaning: "to be able to; can" },
  { word: "真", pinyin: "zhen", meaning: "really; genuinely" },
  { word: "皮", pinyin: "pi", meaning: "leather" },
  { word: "上班族", pinyin: "shangbanzu", meaning: "office worker" },
  { word: "保证书", pinyin: "baozhengshu", meaning: "warranty card" }
];
